Moved Windows node service log collection from automatic to by request. Renamed 'master' to 'control_plane' according to company guidelines.

diff --git a/collection-scripts/gather_service_logs b/collection-scripts/gather_service_logs
--- a/collection-scripts/gather_service_logs
+++ b/collection-scripts/gather_service_logs
@@ -1,40 +1,49 @@
 #!/bin/bash
 BASE_COLLECTION_PATH="/must-gather"
-ROLES=${1:-master}         ### Defaults to only collecting things from Masters
+ROLES=${1:-control_plane_nodes}         ### Defaults to only collecting things from control-plane nodes
 
 # Service Lists
 GENERAL_SERVICES=(kubelet crio)
-MASTER_SERVICES+=${2:-${GENERAL_SERVICES[@]}}
-MASTER_SERVICES+=()        ### Placeholder to extend Master only services
-NODE_SERVICES+=${2:-${GENERAL_SERVICES[@]}}
-NODE_SERVICES+=()          ### Placeholder to extend Node only services
+CONTROL_PLANE_NODE_SERVICES+=${2:-${GENERAL_SERVICES[@]}}
+CONTROL_PLANE_NODE_SERVICES+=()        ### Placeholder to extend control-plane node only services
+COMPUTE_NODE_SERVICES+=${2:-${GENERAL_SERVICES[@]}}
+COMPUTE_NODE_SERVICES+=()          ### Placeholder to extend Node only services
 
 # Collect System Service Logs
 SERVICE_LOG_PATH="${BASE_COLLECTION_PATH}/host_service_logs/"
 
-function collect_serivce_logs {  ## Takes a node role input (master or worker)
+function collect_serivce_logs {  ## Takes a node role input (control_plane_nodes or compute_nodes)
     PIDS=()
-    DIR_PATH=${SERVICE_LOG_PATH}/${1}s
-    echo "WARNING: Collecting one or more service logs on ALL linux $1 nodes in your cluster. This could take a large amount of time." >&2
+    DIR_PATH=${SERVICE_LOG_PATH}/${1}
+
+    if [[ $1 == "compute_nodes" ]]; then
+        DIR_PATH=${DIR_PATH}/linux
+    fi
+
+    echo "WARNING: Collecting one or more service logs on ALL linux $1 in your cluster. This could take a large amount of time." >&2
     mkdir -p ${DIR_PATH}
-    for service in ${NODE_SERVICES[@]}; do
+    COMPUTE_for service in ${NODE_SERVICES[@]}; do
         echo "INFO: Collecting host service logs for $service"
         /usr/bin/oc adm node-logs --role=$1 -l kubernetes.io/os=linux -u $service > ${DIR_PATH}/${service}_service.log &
 	PIDS+=($!)
     done
-    echo "INFO: Waiting for worker host service log collection to complete ..."
+    echo "INFO: Waiting for compute_nodes host service log collection to complete ..."
     wait ${PIDS[@]}
-    echo "INFO: Worker host service log collection to complete."
+    echo "INFO: compute_nodes host service log collection to complete."
 }
 
-if [[ $ROLES == "master" ]]; then
-    collect_serivce_logs master
-elif [[ $ROLES == "worker" ]]; then
-    collect_serivce_logs worker
-elif [[ $ROLES == "master,worker" ]] || [[ $ROLES == "worker,master" ]] ; then
-    collect_serivce_logs master
-    collect_serivce_logs worker
+if [[ $ROLES == "control_plane_nodes" ]]; then
+    collect_serivce_logs control_plane_nodes
+elif [[ $ROLES == "compute_nodes" ]]; then
+    collect_serivce_logs compute_nodes
+    # Gather Windows Kubernetes component logs
+    /usr/bin/gather_windows_node_logs
+elif [[ $ROLES == "control_plane_nodes,compute_nodes" ]] || [[ $ROLES == "compute_nodes,control_plane_nodes" ]] ; then
+    collect_serivce_logs control_plane_nodes
+    collect_serivce_logs compute_nodes
+    # Gather Windows Kubernetes component logs
+    /usr/bin/gather_windows_node_logs
 else
     echo "Error: no role supplied or an invalid role was supplied." >&2
-    echo "Error: valid roles are 'master', 'worker', 'master,worker' or 'worker,master'." >&2
+    echo "Error: valid roles are 'control_plane_nodes', 'compute_nodes', 'control_plane_nodes,compute_nodes' or 'compute_nodes,control_plane_nodes'." >&2
 fi
